// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type PersistentCache struct {
	Key         string
	Body        string
	ContentType string
	ExpiresAt   time.Time
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type UserFavorite struct {
	ID        int64
	UserID    int64
	Url       string
	Title     string
	FeedTitle string
	PubDate   string
	SavedAt   time.Time
}

type UserFeedGroup struct {
	ID       int64
	UserID   int64
	Name     string
	Position int64
}

type UserFeedGroupItem struct {
	ID       int64
	GroupID  int64
	Url      string
	Title    string
	Position int64
}

type UserPreference struct {
	UserID          int64
	FontSize        sql.NullFloat64
	LetterSpacing   sql.NullFloat64
	LineHeight      sql.NullFloat64
	CorsProxyUrl    sql.NullString
	EpubEmbedImages sql.NullInt64
	EmailTo         sql.NullString
	UpdatedAt       time.Time
}

type UserSavedFeed struct {
	ID       int64
	UserID   int64
	Url      string
	Title    string
	Position int64
}
