// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type ArticleArchive struct {
	Key         string
	Title       string
	Author      string
	SiteName    string
	CreatedAt   string
	HtmlContent string
	TextContent string
	ArchivedAt  time.Time
	UpdatedAt   time.Time
}

type FeedItem struct {
	ID            int64
	FeedUrl       string
	ItemUrl       string
	Title         string
	Description   string
	PubDate       string
	ScrapedAt     time.Time
	ArchiveFailed int64
	CommentsUrl   sql.NullString
}

type Session struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type UserFavorite struct {
	ID          int64
	UserID      int64
	Url         string
	Title       string
	FeedTitle   string
	PubDate     string
	CommentsUrl string
	SavedAt     time.Time
}

type UserFeedGroup struct {
	ID       int64
	UserID   int64
	Name     string
	Position int64
}

type UserFeedGroupItem struct {
	ID       int64
	GroupID  int64
	Url      string
	Title    string
	Position int64
}

type UserPreference struct {
	UserID          int64
	FontSize        sql.NullFloat64
	LetterSpacing   sql.NullFloat64
	LineHeight      sql.NullFloat64
	CorsProxyUrl    sql.NullString
	EpubEmbedImages sql.NullInt64
	MobiEmbedImages sql.NullInt64
	EmailTo         sql.NullString
	UpdatedAt       time.Time
}

type UserSavedFeed struct {
	ID             int64
	UserID         int64
	Url            string
	Title          string
	Position       int64
	ArchiveEnabled int64
}
