// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countFeedArchiveItems = `-- name: CountFeedArchiveItems :one
SELECT COUNT(*) FROM feed_items WHERE feed_url = ?
`

func (q *Queries) CountFeedArchiveItems(ctx context.Context, feedUrl string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeedArchiveItems, feedUrl)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash) VALUES (?, ?) RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllUserFavorites = `-- name: DeleteAllUserFavorites :exec
DELETE FROM user_favorites WHERE user_id = ?
`

func (q *Queries) DeleteAllUserFavorites(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserFavorites, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserFeedGroupItems = `-- name: DeleteUserFeedGroupItems :exec
DELETE FROM user_feed_group_items WHERE group_id IN (SELECT id FROM user_feed_groups WHERE user_id = ?)
`

func (q *Queries) DeleteUserFeedGroupItems(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserFeedGroupItems, userID)
	return err
}

const deleteUserFeedGroups = `-- name: DeleteUserFeedGroups :exec
DELETE FROM user_feed_groups WHERE user_id = ?
`

func (q *Queries) DeleteUserFeedGroups(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserFeedGroups, userID)
	return err
}

const deleteUserSavedFeeds = `-- name: DeleteUserSavedFeeds :exec
DELETE FROM user_saved_feeds WHERE user_id = ?
`

func (q *Queries) DeleteUserSavedFeeds(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSavedFeeds, userID)
	return err
}

const getArticleArchive = `-- name: GetArticleArchive :one
SELECT title, author, site_name, created_at, html_content, text_content FROM article_archive WHERE key = ? LIMIT 1
`

type GetArticleArchiveRow struct {
	Title       string
	Author      string
	SiteName    string
	CreatedAt   string
	HtmlContent string
	TextContent string
}

func (q *Queries) GetArticleArchive(ctx context.Context, key string) (GetArticleArchiveRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleArchive, key)
	var i GetArticleArchiveRow
	err := row.Scan(
		&i.Title,
		&i.Author,
		&i.SiteName,
		&i.CreatedAt,
		&i.HtmlContent,
		&i.TextContent,
	)
	return i, err
}

const getDistinctSavedFeedURLs = `-- name: GetDistinctSavedFeedURLs :many
SELECT DISTINCT url FROM user_saved_feeds
`

func (q *Queries) GetDistinctSavedFeedURLs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctSavedFeedURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedArchiveItems = `-- name: GetFeedArchiveItems :many
SELECT item_url, title, description, pub_date, scraped_at, comments_url
FROM feed_items
WHERE feed_url = ?
ORDER BY datetime(pub_date) DESC, scraped_at DESC
LIMIT ? OFFSET ?
`

type GetFeedArchiveItemsParams struct {
	FeedUrl string
	Limit   int64
	Offset  int64
}

type GetFeedArchiveItemsRow struct {
	ItemUrl     string
	Title       string
	Description string
	PubDate     string
	ScrapedAt   time.Time
	CommentsUrl sql.NullString
}

func (q *Queries) GetFeedArchiveItems(ctx context.Context, arg GetFeedArchiveItemsParams) ([]GetFeedArchiveItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedArchiveItems, arg.FeedUrl, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedArchiveItemsRow
	for rows.Next() {
		var i GetFeedArchiveItemsRow
		if err := rows.Scan(
			&i.ItemUrl,
			&i.Title,
			&i.Description,
			&i.PubDate,
			&i.ScrapedAt,
			&i.CommentsUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedGroupItems = `-- name: GetFeedGroupItems :many
SELECT url, title FROM user_feed_group_items WHERE group_id = ? ORDER BY position
`

type GetFeedGroupItemsRow struct {
	Url   string
	Title string
}

func (q *Queries) GetFeedGroupItems(ctx context.Context, groupID int64) ([]GetFeedGroupItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedGroupItems, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedGroupItemsRow
	for rows.Next() {
		var i GetFeedGroupItemsRow
		if err := rows.Scan(&i.Url, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFeedItemWithoutArchive = `-- name: GetNextFeedItemWithoutArchive :one
SELECT item_url FROM feed_items
WHERE item_url NOT IN (SELECT key FROM article_archive)
AND archive_failed = 0
LIMIT 1
`

func (q *Queries) GetNextFeedItemWithoutArchive(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedItemWithoutArchive)
	var item_url string
	err := row.Scan(&item_url)
	return item_url, err
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at FROM sessions WHERE token = ? AND expires_at > CURRENT_TIMESTAMP LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(&i.Token, &i.UserID, &i.ExpiresAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserFavorites = `-- name: GetUserFavorites :many
SELECT url, title, feed_title, pub_date, comments_url FROM user_favorites WHERE user_id = ? ORDER BY saved_at DESC
`

type GetUserFavoritesRow struct {
	Url         string
	Title       string
	FeedTitle   string
	PubDate     string
	CommentsUrl string
}

func (q *Queries) GetUserFavorites(ctx context.Context, userID int64) ([]GetUserFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFavoritesRow
	for rows.Next() {
		var i GetUserFavoritesRow
		if err := rows.Scan(
			&i.Url,
			&i.Title,
			&i.FeedTitle,
			&i.PubDate,
			&i.CommentsUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFeedGroups = `-- name: GetUserFeedGroups :many
SELECT id, name FROM user_feed_groups WHERE user_id = ? ORDER BY position
`

type GetUserFeedGroupsRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetUserFeedGroups(ctx context.Context, userID int64) ([]GetUserFeedGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeedGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedGroupsRow
	for rows.Next() {
		var i GetUserFeedGroupsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT font_size, letter_spacing, line_height, cors_proxy_url, epub_embed_images, email_to
FROM user_preferences WHERE user_id = ? LIMIT 1
`

type GetUserPreferencesRow struct {
	FontSize        sql.NullFloat64
	LetterSpacing   sql.NullFloat64
	LineHeight      sql.NullFloat64
	CorsProxyUrl    sql.NullString
	EpubEmbedImages sql.NullInt64
	EmailTo         sql.NullString
}

func (q *Queries) GetUserPreferences(ctx context.Context, userID int64) (GetUserPreferencesRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i GetUserPreferencesRow
	err := row.Scan(
		&i.FontSize,
		&i.LetterSpacing,
		&i.LineHeight,
		&i.CorsProxyUrl,
		&i.EpubEmbedImages,
		&i.EmailTo,
	)
	return i, err
}

const getUserSavedFeeds = `-- name: GetUserSavedFeeds :many
SELECT url, title FROM user_saved_feeds WHERE user_id = ? ORDER BY position
`

type GetUserSavedFeedsRow struct {
	Url   string
	Title string
}

func (q *Queries) GetUserSavedFeeds(ctx context.Context, userID int64) ([]GetUserSavedFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserSavedFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSavedFeedsRow
	for rows.Next() {
		var i GetUserSavedFeedsRow
		if err := rows.Scan(&i.Url, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFeedGroup = `-- name: InsertFeedGroup :one
INSERT INTO user_feed_groups (user_id, name, position) VALUES (?, ?, ?) RETURNING id
`

type InsertFeedGroupParams struct {
	UserID   int64
	Name     string
	Position int64
}

func (q *Queries) InsertFeedGroup(ctx context.Context, arg InsertFeedGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertFeedGroup, arg.UserID, arg.Name, arg.Position)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertFeedGroupItem = `-- name: InsertFeedGroupItem :exec
INSERT INTO user_feed_group_items (group_id, url, title, position) VALUES (?, ?, ?, ?)
`

type InsertFeedGroupItemParams struct {
	GroupID  int64
	Url      string
	Title    string
	Position int64
}

func (q *Queries) InsertFeedGroupItem(ctx context.Context, arg InsertFeedGroupItemParams) error {
	_, err := q.db.ExecContext(ctx, insertFeedGroupItem,
		arg.GroupID,
		arg.Url,
		arg.Title,
		arg.Position,
	)
	return err
}

const insertFeedItem = `-- name: InsertFeedItem :execresult
INSERT OR IGNORE INTO feed_items (feed_url, item_url, title, description, pub_date, comments_url)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertFeedItemParams struct {
	FeedUrl     string
	ItemUrl     string
	Title       string
	Description string
	PubDate     string
	CommentsUrl sql.NullString
}

func (q *Queries) InsertFeedItem(ctx context.Context, arg InsertFeedItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertFeedItem,
		arg.FeedUrl,
		arg.ItemUrl,
		arg.Title,
		arg.Description,
		arg.PubDate,
		arg.CommentsUrl,
	)
}

const insertUserFavorite = `-- name: InsertUserFavorite :exec
INSERT INTO user_favorites (user_id, url, title, feed_title, pub_date, comments_url) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertUserFavoriteParams struct {
	UserID      int64
	Url         string
	Title       string
	FeedTitle   string
	PubDate     string
	CommentsUrl string
}

func (q *Queries) InsertUserFavorite(ctx context.Context, arg InsertUserFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, insertUserFavorite,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.FeedTitle,
		arg.PubDate,
		arg.CommentsUrl,
	)
	return err
}

const insertUserSavedFeed = `-- name: InsertUserSavedFeed :exec
INSERT INTO user_saved_feeds (user_id, url, title, position) VALUES (?, ?, ?, ?)
`

type InsertUserSavedFeedParams struct {
	UserID   int64
	Url      string
	Title    string
	Position int64
}

func (q *Queries) InsertUserSavedFeed(ctx context.Context, arg InsertUserSavedFeedParams) error {
	_, err := q.db.ExecContext(ctx, insertUserSavedFeed,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.Position,
	)
	return err
}

const markFeedItemArchiveFailed = `-- name: MarkFeedItemArchiveFailed :exec
UPDATE feed_items SET archive_failed = 1 WHERE item_url = ?
`

func (q *Queries) MarkFeedItemArchiveFailed(ctx context.Context, itemUrl string) error {
	_, err := q.db.ExecContext(ctx, markFeedItemArchiveFailed, itemUrl)
	return err
}

const upsertArticleArchive = `-- name: UpsertArticleArchive :exec
INSERT INTO article_archive (key, title, author, site_name, created_at, html_content, text_content) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET title = excluded.title, author = excluded.author, site_name = excluded.site_name, created_at = excluded.created_at, html_content = excluded.html_content, text_content = excluded.text_content, updated_at = CURRENT_TIMESTAMP
`

type UpsertArticleArchiveParams struct {
	Key         string
	Title       string
	Author      string
	SiteName    string
	CreatedAt   string
	HtmlContent string
	TextContent string
}

func (q *Queries) UpsertArticleArchive(ctx context.Context, arg UpsertArticleArchiveParams) error {
	_, err := q.db.ExecContext(ctx, upsertArticleArchive,
		arg.Key,
		arg.Title,
		arg.Author,
		arg.SiteName,
		arg.CreatedAt,
		arg.HtmlContent,
		arg.TextContent,
	)
	return err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (user_id, font_size, letter_spacing, line_height, cors_proxy_url, epub_embed_images, email_to, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(user_id) DO UPDATE SET
    font_size = excluded.font_size,
    letter_spacing = excluded.letter_spacing,
    line_height = excluded.line_height,
    cors_proxy_url = excluded.cors_proxy_url,
    epub_embed_images = excluded.epub_embed_images,
    email_to = excluded.email_to,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserPreferencesParams struct {
	UserID          int64
	FontSize        sql.NullFloat64
	LetterSpacing   sql.NullFloat64
	LineHeight      sql.NullFloat64
	CorsProxyUrl    sql.NullString
	EpubEmbedImages sql.NullInt64
	EmailTo         sql.NullString
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPreferences,
		arg.UserID,
		arg.FontSize,
		arg.LetterSpacing,
		arg.LineHeight,
		arg.CorsProxyUrl,
		arg.EpubEmbedImages,
		arg.EmailTo,
	)
	return err
}
